/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/schema/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description OpenApi3 schema for this API. Format can be selected via content negotiation.
         *
         *     - YAML: application/vnd.oai.openapi
         *     - JSON: application/vnd.oai.openapi+json
         */
        get: operations["api_schema_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/attendance/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Simply wires GroupPermission into any ModelViewSet.
         *     Subclasses only need to declare resource_name.
         *
         *     Example:
         *         class SessionViewset(GroupRBACMixin, ModelViewSet):
         *             resource_name = "session"
         */
        get: operations["attendance_list"];
        put?: never;
        /**
         * @description Simply wires GroupPermission into any ModelViewSet.
         *     Subclasses only need to declare resource_name.
         *
         *     Example:
         *         class SessionViewset(GroupRBACMixin, ModelViewSet):
         *             resource_name = "session"
         */
        post: operations["attendance_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/attendance/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Simply wires GroupPermission into any ModelViewSet.
         *     Subclasses only need to declare resource_name.
         *
         *     Example:
         *         class SessionViewset(GroupRBACMixin, ModelViewSet):
         *             resource_name = "session"
         */
        get: operations["attendance_retrieve"];
        /**
         * @description Simply wires GroupPermission into any ModelViewSet.
         *     Subclasses only need to declare resource_name.
         *
         *     Example:
         *         class SessionViewset(GroupRBACMixin, ModelViewSet):
         *             resource_name = "session"
         */
        put: operations["attendance_update"];
        post?: never;
        /**
         * @description Simply wires GroupPermission into any ModelViewSet.
         *     Subclasses only need to declare resource_name.
         *
         *     Example:
         *         class SessionViewset(GroupRBACMixin, ModelViewSet):
         *             resource_name = "session"
         */
        delete: operations["attendance_destroy"];
        options?: never;
        head?: never;
        /**
         * @description Simply wires GroupPermission into any ModelViewSet.
         *     Subclasses only need to declare resource_name.
         *
         *     Example:
         *         class SessionViewset(GroupRBACMixin, ModelViewSet):
         *             resource_name = "session"
         */
        patch: operations["attendance_partial_update"];
        trace?: never;
    };
    "/attendance/heartbeat/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Simply wires GroupPermission into any ModelViewSet.
         *     Subclasses only need to declare resource_name.
         *
         *     Example:
         *         class SessionViewset(GroupRBACMixin, ModelViewSet):
         *             resource_name = "session"
         */
        post: operations["attendance_heartbeat_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/google/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auth_google_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/token/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Takes a set of user credentials and returns an access and refresh JSON web
         *     token pair to prove the authentication of those credentials.
         */
        post: operations["auth_token_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/token/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Takes a refresh type JSON web token and returns an access type JSON web
         *     token if the refresh token is valid.
         */
        post: operations["auth_token_refresh_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["chat_list"];
        put?: never;
        post: operations["chat_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["chat_retrieve"];
        put: operations["chat_update"];
        post?: never;
        delete: operations["chat_destroy"];
        options?: never;
        head?: never;
        patch: operations["chat_partial_update"];
        trace?: never;
    };
    "/membership/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Simply wires GroupPermission into any ModelViewSet.
         *     Subclasses only need to declare resource_name.
         *
         *     Example:
         *         class SessionViewset(GroupRBACMixin, ModelViewSet):
         *             resource_name = "session"
         */
        get: operations["membership_list"];
        put?: never;
        /**
         * @description Simply wires GroupPermission into any ModelViewSet.
         *     Subclasses only need to declare resource_name.
         *
         *     Example:
         *         class SessionViewset(GroupRBACMixin, ModelViewSet):
         *             resource_name = "session"
         */
        post: operations["membership_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/membership/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Simply wires GroupPermission into any ModelViewSet.
         *     Subclasses only need to declare resource_name.
         *
         *     Example:
         *         class SessionViewset(GroupRBACMixin, ModelViewSet):
         *             resource_name = "session"
         */
        get: operations["membership_retrieve"];
        /**
         * @description Simply wires GroupPermission into any ModelViewSet.
         *     Subclasses only need to declare resource_name.
         *
         *     Example:
         *         class SessionViewset(GroupRBACMixin, ModelViewSet):
         *             resource_name = "session"
         */
        put: operations["membership_update"];
        post?: never;
        /**
         * @description Simply wires GroupPermission into any ModelViewSet.
         *     Subclasses only need to declare resource_name.
         *
         *     Example:
         *         class SessionViewset(GroupRBACMixin, ModelViewSet):
         *             resource_name = "session"
         */
        delete: operations["membership_destroy"];
        options?: never;
        head?: never;
        /**
         * @description Simply wires GroupPermission into any ModelViewSet.
         *     Subclasses only need to declare resource_name.
         *
         *     Example:
         *         class SessionViewset(GroupRBACMixin, ModelViewSet):
         *             resource_name = "session"
         */
        patch: operations["membership_partial_update"];
        trace?: never;
    };
    "/membership/stats/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Returns membership counts grouped by status for a given group. */
        get: operations["membership_stats_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/membership/update_member_role/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Simply wires GroupPermission into any ModelViewSet.
         *     Subclasses only need to declare resource_name.
         *
         *     Example:
         *         class SessionViewset(GroupRBACMixin, ModelViewSet):
         *             resource_name = "session"
         */
        post: operations["membership_update_member_role_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/membership/update_member_status/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Simply wires GroupPermission into any ModelViewSet.
         *     Subclasses only need to declare resource_name.
         *
         *     Example:
         *         class SessionViewset(GroupRBACMixin, ModelViewSet):
         *             resource_name = "session"
         */
        post: operations["membership_update_member_status_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notification/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["notification_list"];
        put?: never;
        post: operations["notification_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notification/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["notification_retrieve"];
        put: operations["notification_update"];
        post?: never;
        delete: operations["notification_destroy"];
        options?: never;
        head?: never;
        patch: operations["notification_partial_update"];
        trace?: never;
    };
    "/session/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Simply wires GroupPermission into any ModelViewSet.
         *     Subclasses only need to declare resource_name.
         *
         *     Example:
         *         class SessionViewset(GroupRBACMixin, ModelViewSet):
         *             resource_name = "session"
         */
        get: operations["session_list"];
        put?: never;
        /**
         * @description Simply wires GroupPermission into any ModelViewSet.
         *     Subclasses only need to declare resource_name.
         *
         *     Example:
         *         class SessionViewset(GroupRBACMixin, ModelViewSet):
         *             resource_name = "session"
         */
        post: operations["session_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/session/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Simply wires GroupPermission into any ModelViewSet.
         *     Subclasses only need to declare resource_name.
         *
         *     Example:
         *         class SessionViewset(GroupRBACMixin, ModelViewSet):
         *             resource_name = "session"
         */
        get: operations["session_retrieve"];
        /**
         * @description Simply wires GroupPermission into any ModelViewSet.
         *     Subclasses only need to declare resource_name.
         *
         *     Example:
         *         class SessionViewset(GroupRBACMixin, ModelViewSet):
         *             resource_name = "session"
         */
        put: operations["session_update"];
        post?: never;
        /**
         * @description Simply wires GroupPermission into any ModelViewSet.
         *     Subclasses only need to declare resource_name.
         *
         *     Example:
         *         class SessionViewset(GroupRBACMixin, ModelViewSet):
         *             resource_name = "session"
         */
        delete: operations["session_destroy"];
        options?: never;
        head?: never;
        /**
         * @description Simply wires GroupPermission into any ModelViewSet.
         *     Subclasses only need to declare resource_name.
         *
         *     Example:
         *         class SessionViewset(GroupRBACMixin, ModelViewSet):
         *             resource_name = "session"
         */
        patch: operations["session_partial_update"];
        trace?: never;
    };
    "/session/join/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Simply wires GroupPermission into any ModelViewSet.
         *     Subclasses only need to declare resource_name.
         *
         *     Example:
         *         class SessionViewset(GroupRBACMixin, ModelViewSet):
         *             resource_name = "session"
         */
        post: operations["session_join_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/session/leave/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Simply wires GroupPermission into any ModelViewSet.
         *     Subclasses only need to declare resource_name.
         *
         *     Example:
         *         class SessionViewset(GroupRBACMixin, ModelViewSet):
         *             resource_name = "session"
         */
        post: operations["session_leave_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/session/upcoming/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Simply wires GroupPermission into any ModelViewSet.
         *     Subclasses only need to declare resource_name.
         *
         *     Example:
         *         class SessionViewset(GroupRBACMixin, ModelViewSet):
         *             resource_name = "session"
         */
        get: operations["session_upcoming_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/study-group/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Simply wires GroupPermission into any ModelViewSet.
         *     Subclasses only need to declare resource_name.
         *
         *     Example:
         *         class SessionViewset(GroupRBACMixin, ModelViewSet):
         *             resource_name = "session"
         */
        get: operations["study_group_list"];
        put?: never;
        /**
         * @description Simply wires GroupPermission into any ModelViewSet.
         *     Subclasses only need to declare resource_name.
         *
         *     Example:
         *         class SessionViewset(GroupRBACMixin, ModelViewSet):
         *             resource_name = "session"
         */
        post: operations["study_group_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/study-group/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Simply wires GroupPermission into any ModelViewSet.
         *     Subclasses only need to declare resource_name.
         *
         *     Example:
         *         class SessionViewset(GroupRBACMixin, ModelViewSet):
         *             resource_name = "session"
         */
        get: operations["study_group_retrieve"];
        /**
         * @description Simply wires GroupPermission into any ModelViewSet.
         *     Subclasses only need to declare resource_name.
         *
         *     Example:
         *         class SessionViewset(GroupRBACMixin, ModelViewSet):
         *             resource_name = "session"
         */
        put: operations["study_group_update"];
        post?: never;
        /**
         * @description Simply wires GroupPermission into any ModelViewSet.
         *     Subclasses only need to declare resource_name.
         *
         *     Example:
         *         class SessionViewset(GroupRBACMixin, ModelViewSet):
         *             resource_name = "session"
         */
        delete: operations["study_group_destroy"];
        options?: never;
        head?: never;
        /**
         * @description Simply wires GroupPermission into any ModelViewSet.
         *     Subclasses only need to declare resource_name.
         *
         *     Example:
         *         class SessionViewset(GroupRBACMixin, ModelViewSet):
         *             resource_name = "session"
         */
        patch: operations["study_group_partial_update"];
        trace?: never;
    };
    "/study-group/{id}/attendance_history/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Simply wires GroupPermission into any ModelViewSet.
         *     Subclasses only need to declare resource_name.
         *
         *     Example:
         *         class SessionViewset(GroupRBACMixin, ModelViewSet):
         *             resource_name = "session"
         */
        get: operations["study_group_attendance_history_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/study-group/{id}/cancel_request/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Simply wires GroupPermission into any ModelViewSet.
         *     Subclasses only need to declare resource_name.
         *
         *     Example:
         *         class SessionViewset(GroupRBACMixin, ModelViewSet):
         *             resource_name = "session"
         */
        post: operations["study_group_cancel_request_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/study-group/{id}/join_request/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Simply wires GroupPermission into any ModelViewSet.
         *     Subclasses only need to declare resource_name.
         *
         *     Example:
         *         class SessionViewset(GroupRBACMixin, ModelViewSet):
         *             resource_name = "session"
         */
        post: operations["study_group_join_request_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/study-group/{id}/sessions_list/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Simply wires GroupPermission into any ModelViewSet.
         *     Subclasses only need to declare resource_name.
         *
         *     Example:
         *         class SessionViewset(GroupRBACMixin, ModelViewSet):
         *             resource_name = "session"
         */
        get: operations["study_group_sessions_list_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/study-group/invite/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Simply wires GroupPermission into any ModelViewSet.
         *     Subclasses only need to declare resource_name.
         *
         *     Example:
         *         class SessionViewset(GroupRBACMixin, ModelViewSet):
         *             resource_name = "session"
         */
        post: operations["study_group_invite_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/subject/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["subject_list"];
        put?: never;
        post: operations["subject_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/subject/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["subject_retrieve"];
        put: operations["subject_update"];
        post?: never;
        delete: operations["subject_destroy"];
        options?: never;
        head?: never;
        patch: operations["subject_partial_update"];
        trace?: never;
    };
    "/user/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["user_list"];
        put?: never;
        post: operations["user_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["user_retrieve"];
        put: operations["user_update"];
        post?: never;
        delete: operations["user_destroy"];
        options?: never;
        head?: never;
        patch: operations["user_partial_update"];
        trace?: never;
    };
    "/user/{id}/profile/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["user_profile_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/me/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["user_me_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/stats/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["user_stats_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Attendance: {
            readonly id: number;
            readonly group_detail: components["schemas"]["StudyGroup"];
            readonly user_detail: components["schemas"]["SimpleUser"];
            readonly session_detail: components["schemas"]["Session"];
            group: number;
            user: number;
            session: number;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
            status?: components["schemas"]["AttendanceStatusEnum"];
            is_active?: boolean;
            /** Format: date-time */
            check_in_time?: string;
            /** Format: date-time */
            check_out_time?: string | null;
            total_active_seconds?: number;
            /** Format: date-time */
            last_active?: string | null;
        };
        /**
         * @description * `present` - Present
         *     * `absent` - Absent
         *     * `late` - Late
         * @enum {string}
         */
        AttendanceStatusEnum: "present" | "absent" | "late";
        Chat: {
            readonly id: number;
            readonly sender: components["schemas"]["SenderSchema"];
            readonly reply_to: components["schemas"]["ReplyToSchema"] | null;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
            object_id?: number | null;
            attachments?: string | null;
            message?: string | null;
            content_type?: number | null;
        };
        MemberShip: {
            readonly id: number;
            readonly user: components["schemas"]["SimpleUser"];
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
            status?: components["schemas"]["MembershipStatusEnum"];
            role?: components["schemas"]["RoleEnum"];
            group: number;
        };
        /**
         * @description * `accepted` - Accepted
         *     * `rejected` - Rejected
         *     * `pending` - Pending
         *     * `cancelled` - Cancelled
         * @enum {string}
         */
        MembershipStatusEnum: "accepted" | "rejected" | "pending" | "cancelled";
        Notification: {
            readonly id: number;
            to: components["schemas"]["User"];
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
            content: string;
            is_read?: boolean;
        };
        PaginatedAttendanceList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Attendance"][];
        };
        PaginatedChatList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Chat"][];
        };
        PaginatedMemberShipList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["MemberShip"][];
        };
        PaginatedNotificationList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Notification"][];
        };
        PaginatedSessionList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Session"][];
        };
        PaginatedSimpleUserList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["SimpleUser"][];
        };
        PaginatedStudyGroupList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["StudyGroup"][];
        };
        PaginatedSubjectList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Subject"][];
        };
        PatchedAttendance: {
            readonly id?: number;
            readonly group_detail?: components["schemas"]["StudyGroup"];
            readonly user_detail?: components["schemas"]["SimpleUser"];
            readonly session_detail?: components["schemas"]["Session"];
            group?: number;
            user?: number;
            session?: number;
            /** Format: date-time */
            readonly created_at?: string;
            /** Format: date-time */
            readonly updated_at?: string;
            status?: components["schemas"]["AttendanceStatusEnum"];
            is_active?: boolean;
            /** Format: date-time */
            check_in_time?: string;
            /** Format: date-time */
            check_out_time?: string | null;
            total_active_seconds?: number;
            /** Format: date-time */
            last_active?: string | null;
        };
        PatchedChat: {
            readonly id?: number;
            readonly sender?: components["schemas"]["SenderSchema"];
            readonly reply_to?: components["schemas"]["ReplyToSchema"] | null;
            /** Format: date-time */
            readonly created_at?: string;
            /** Format: date-time */
            readonly updated_at?: string;
            object_id?: number | null;
            attachments?: string | null;
            message?: string | null;
            content_type?: number | null;
        };
        PatchedMemberShip: {
            readonly id?: number;
            readonly user?: components["schemas"]["SimpleUser"];
            /** Format: date-time */
            readonly created_at?: string;
            /** Format: date-time */
            readonly updated_at?: string;
            status?: components["schemas"]["MembershipStatusEnum"];
            role?: components["schemas"]["RoleEnum"];
            group?: number;
        };
        PatchedNotification: {
            readonly id?: number;
            to?: components["schemas"]["User"];
            /** Format: date-time */
            readonly created_at?: string;
            /** Format: date-time */
            readonly updated_at?: string;
            content?: string;
            is_read?: boolean;
        };
        PatchedSession: {
            readonly id?: number;
            readonly group_detail?: components["schemas"]["StudyGroupSimple"];
            group?: number;
            /** Format: date-time */
            readonly created_at?: string;
            /** Format: date-time */
            readonly updated_at?: string;
            session_type?: components["schemas"]["SessionTypeEnum"];
            status?: components["schemas"]["SessionStatusEnum"];
            /** Format: date-time */
            start?: string;
            /** Format: date-time */
            end?: string;
            location?: string | null;
            notes?: string;
        };
        PatchedSimpleUser: {
            readonly id?: number;
            username?: string | null;
            first_name?: string;
            last_name?: string;
            /**
             * Email address
             * Format: email
             */
            email?: string;
            /** Format: uri */
            avatar?: string | null;
        };
        PatchedStudyGroup: {
            readonly id?: number;
            readonly creator_detail?: components["schemas"]["SimpleUser"];
            readonly subject_detail?: components["schemas"]["Subject"];
            readonly memberships?: components["schemas"]["MemberShip"][];
            creator?: number;
            subject?: number;
            readonly next_session?: components["schemas"]["SessionSimple"] | null;
            readonly total_sessions?: number;
            readonly membership_status?: string | null;
            /** Format: date-time */
            readonly created_at?: string;
            /** Format: date-time */
            readonly updated_at?: string;
            name?: string;
            description?: string;
            max_members?: number;
        };
        PatchedSubject: {
            readonly id?: number;
            /** Format: date-time */
            readonly created_at?: string;
            /** Format: date-time */
            readonly updated_at?: string;
            name?: string;
        };
        ReplyToSchema: {
            id: number;
            message: string | null;
            attachments: string | null;
            sender: components["schemas"]["SenderSchema"];
        };
        /**
         * @description * `creator` - Creator
         *     * `moderator` - Moderator
         *     * `member` - Member
         * @enum {string}
         */
        RoleEnum: "creator" | "moderator" | "member";
        SenderSchema: {
            id: number;
            first_name: string;
            last_name: string;
            /** Format: email */
            email: string;
            avatar: string | null;
        };
        Session: {
            readonly id: number;
            readonly group_detail: components["schemas"]["StudyGroupSimple"];
            group: number;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
            session_type?: components["schemas"]["SessionTypeEnum"];
            status?: components["schemas"]["SessionStatusEnum"];
            /** Format: date-time */
            start: string;
            /** Format: date-time */
            end: string;
            location?: string | null;
            notes: string;
        };
        SessionSimple: {
            readonly id: number;
            /** Format: date-time */
            start: string;
            /** Format: date-time */
            end: string;
            status?: components["schemas"]["SessionStatusEnum"];
        };
        /**
         * @description * `finished` - Finished
         *     * `scheduled` - Scheduled
         *     * `on_going` - On Going
         *     * `cancelled` - Cancelled
         * @enum {string}
         */
        SessionStatusEnum: "finished" | "scheduled" | "on_going" | "cancelled";
        /**
         * @description * `online` - Online
         *     * `physical` - Physical
         * @enum {string}
         */
        SessionTypeEnum: "online" | "physical";
        SimpleUser: {
            readonly id: number;
            username?: string | null;
            first_name: string;
            last_name: string;
            /**
             * Email address
             * Format: email
             */
            email: string;
            /** Format: uri */
            avatar?: string | null;
        };
        StudyGroup: {
            readonly id: number;
            readonly creator_detail: components["schemas"]["SimpleUser"];
            readonly subject_detail: components["schemas"]["Subject"];
            readonly memberships: components["schemas"]["MemberShip"][];
            creator: number;
            subject: number;
            readonly next_session: components["schemas"]["SessionSimple"] | null;
            readonly total_sessions: number;
            readonly membership_status: string | null;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
            name: string;
            description: string;
            max_members?: number;
        };
        StudyGroupSimple: {
            readonly id: number;
            name: string;
            description: string;
        };
        Subject: {
            readonly id: number;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
            name: string;
        };
        TokenObtainPair: {
            email: string;
            password: string;
            readonly access: string;
            readonly refresh: string;
        };
        TokenRefresh: {
            readonly access: string;
            refresh: string;
        };
        User: {
            readonly id: number;
            password: string;
            /**
             * Superuser status
             * @description Designates that this user has all permissions without explicitly assigning them.
             */
            is_superuser?: boolean;
            username?: string | null;
            last_name: string;
            first_name: string;
            /**
             * Email address
             * Format: email
             */
            email: string;
            /** Format: uri */
            avatar?: string | null;
            is_active?: boolean;
            is_admin?: boolean;
            /** Format: date-time */
            date_joined?: string;
            /** Format: date-time */
            last_login?: string;
            /** @description The groups this user belongs to. A user will get all permissions granted to each of their groups. */
            groups?: number[];
            /** @description Specific permissions for this user. */
            user_permissions?: number[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    api_schema_retrieve: {
        parameters: {
            query?: {
                format?: "json" | "yaml";
                lang?: "af" | "ar" | "ar-dz" | "ast" | "az" | "be" | "bg" | "bn" | "br" | "bs" | "ca" | "ckb" | "cs" | "cy" | "da" | "de" | "dsb" | "el" | "en" | "en-au" | "en-gb" | "eo" | "es" | "es-ar" | "es-co" | "es-mx" | "es-ni" | "es-ve" | "et" | "eu" | "fa" | "fi" | "fr" | "fy" | "ga" | "gd" | "gl" | "he" | "hi" | "hr" | "hsb" | "hu" | "hy" | "ia" | "id" | "ig" | "io" | "is" | "it" | "ja" | "ka" | "kab" | "kk" | "km" | "kn" | "ko" | "ky" | "lb" | "lt" | "lv" | "mk" | "ml" | "mn" | "mr" | "ms" | "my" | "nb" | "ne" | "nl" | "nn" | "os" | "pa" | "pl" | "pt" | "pt-br" | "ro" | "ru" | "sk" | "sl" | "sq" | "sr" | "sr-latn" | "sv" | "sw" | "ta" | "te" | "tg" | "th" | "tk" | "tr" | "tt" | "udm" | "ug" | "uk" | "ur" | "uz" | "vi" | "zh-hans" | "zh-hant";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.oai.openapi": {
                        [key: string]: unknown;
                    };
                    "application/yaml": {
                        [key: string]: unknown;
                    };
                    "application/vnd.oai.openapi+json": {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    attendance_list: {
        parameters: {
            query?: {
                group?: number;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
                session?: number;
                user?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedAttendanceList"];
                };
            };
        };
    };
    attendance_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Attendance"];
                "application/x-www-form-urlencoded": components["schemas"]["Attendance"];
                "multipart/form-data": components["schemas"]["Attendance"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Attendance"];
                };
            };
        };
    };
    attendance_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this attendance. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Attendance"];
                };
            };
        };
    };
    attendance_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this attendance. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Attendance"];
                "application/x-www-form-urlencoded": components["schemas"]["Attendance"];
                "multipart/form-data": components["schemas"]["Attendance"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Attendance"];
                };
            };
        };
    };
    attendance_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this attendance. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    attendance_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this attendance. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedAttendance"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedAttendance"];
                "multipart/form-data": components["schemas"]["PatchedAttendance"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Attendance"];
                };
            };
        };
    };
    attendance_heartbeat_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Attendance"];
                "application/x-www-form-urlencoded": components["schemas"]["Attendance"];
                "multipart/form-data": components["schemas"]["Attendance"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Attendance"];
                };
            };
        };
    };
    auth_google_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_token_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenObtainPair"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenObtainPair"];
                "multipart/form-data": components["schemas"]["TokenObtainPair"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenObtainPair"];
                };
            };
        };
    };
    auth_token_refresh_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenRefresh"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenRefresh"];
                "multipart/form-data": components["schemas"]["TokenRefresh"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenRefresh"];
                };
            };
        };
    };
    chat_list: {
        parameters: {
            query?: {
                group?: number;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
                sender?: number;
                session?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedChatList"];
                };
            };
        };
    };
    chat_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["Chat"];
                "application/x-www-form-urlencoded": components["schemas"]["Chat"];
                "multipart/form-data": components["schemas"]["Chat"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Chat"];
                };
            };
        };
    };
    chat_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this chat. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Chat"];
                };
            };
        };
    };
    chat_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this chat. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["Chat"];
                "application/x-www-form-urlencoded": components["schemas"]["Chat"];
                "multipart/form-data": components["schemas"]["Chat"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Chat"];
                };
            };
        };
    };
    chat_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this chat. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    chat_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this chat. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedChat"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedChat"];
                "multipart/form-data": components["schemas"]["PatchedChat"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Chat"];
                };
            };
        };
    };
    membership_list: {
        parameters: {
            query?: {
                group?: number;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
                /**
                 * @description * `creator` - Creator
                 *     * `moderator` - Moderator
                 *     * `member` - Member
                 */
                role?: "creator" | "member" | "moderator";
                /**
                 * @description * `accepted` - Accepted
                 *     * `rejected` - Rejected
                 *     * `pending` - Pending
                 *     * `cancelled` - Cancelled
                 */
                status?: "accepted" | "cancelled" | "pending" | "rejected";
                user?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedMemberShipList"];
                };
            };
        };
    };
    membership_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemberShip"];
                "application/x-www-form-urlencoded": components["schemas"]["MemberShip"];
                "multipart/form-data": components["schemas"]["MemberShip"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberShip"];
                };
            };
        };
    };
    membership_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this member ship. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberShip"];
                };
            };
        };
    };
    membership_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this member ship. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemberShip"];
                "application/x-www-form-urlencoded": components["schemas"]["MemberShip"];
                "multipart/form-data": components["schemas"]["MemberShip"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberShip"];
                };
            };
        };
    };
    membership_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this member ship. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    membership_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this member ship. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedMemberShip"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedMemberShip"];
                "multipart/form-data": components["schemas"]["PatchedMemberShip"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberShip"];
                };
            };
        };
    };
    membership_stats_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberShip"];
                };
            };
        };
    };
    membership_update_member_role_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemberShip"];
                "application/x-www-form-urlencoded": components["schemas"]["MemberShip"];
                "multipart/form-data": components["schemas"]["MemberShip"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberShip"];
                };
            };
        };
    };
    membership_update_member_status_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemberShip"];
                "application/x-www-form-urlencoded": components["schemas"]["MemberShip"];
                "multipart/form-data": components["schemas"]["MemberShip"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberShip"];
                };
            };
        };
    };
    notification_list: {
        parameters: {
            query?: {
                is_read?: boolean;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedNotificationList"];
                };
            };
        };
    };
    notification_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Notification"];
                "application/x-www-form-urlencoded": components["schemas"]["Notification"];
                "multipart/form-data": components["schemas"]["Notification"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Notification"];
                };
            };
        };
    };
    notification_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this notification. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Notification"];
                };
            };
        };
    };
    notification_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this notification. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Notification"];
                "application/x-www-form-urlencoded": components["schemas"]["Notification"];
                "multipart/form-data": components["schemas"]["Notification"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Notification"];
                };
            };
        };
    };
    notification_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this notification. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    notification_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this notification. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedNotification"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedNotification"];
                "multipart/form-data": components["schemas"]["PatchedNotification"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Notification"];
                };
            };
        };
    };
    session_list: {
        parameters: {
            query?: {
                group?: number;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
                /**
                 * @description * `online` - Online
                 *     * `physical` - Physical
                 */
                session_type?: "online" | "physical";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedSessionList"];
                };
            };
        };
    };
    session_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Session"];
                "application/x-www-form-urlencoded": components["schemas"]["Session"];
                "multipart/form-data": components["schemas"]["Session"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
        };
    };
    session_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this session. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
        };
    };
    session_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this session. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Session"];
                "application/x-www-form-urlencoded": components["schemas"]["Session"];
                "multipart/form-data": components["schemas"]["Session"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
        };
    };
    session_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this session. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    session_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this session. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedSession"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedSession"];
                "multipart/form-data": components["schemas"]["PatchedSession"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
        };
    };
    session_join_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Session"];
                "application/x-www-form-urlencoded": components["schemas"]["Session"];
                "multipart/form-data": components["schemas"]["Session"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
        };
    };
    session_leave_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Session"];
                "application/x-www-form-urlencoded": components["schemas"]["Session"];
                "multipart/form-data": components["schemas"]["Session"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
        };
    };
    session_upcoming_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
        };
    };
    study_group_list: {
        parameters: {
            query?: {
                creator?: number;
                max_members?: number;
                /**
                 * @description * `creator` - Creator
                 *     * `moderator` - Moderator
                 *     * `member` - Member
                 */
                memberships__role?: "creator" | "member" | "moderator";
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
                subject?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedStudyGroupList"];
                };
            };
        };
    };
    study_group_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StudyGroup"];
                "application/x-www-form-urlencoded": components["schemas"]["StudyGroup"];
                "multipart/form-data": components["schemas"]["StudyGroup"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudyGroup"];
                };
            };
        };
    };
    study_group_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this study group. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudyGroup"];
                };
            };
        };
    };
    study_group_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this study group. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StudyGroup"];
                "application/x-www-form-urlencoded": components["schemas"]["StudyGroup"];
                "multipart/form-data": components["schemas"]["StudyGroup"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudyGroup"];
                };
            };
        };
    };
    study_group_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this study group. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    study_group_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this study group. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedStudyGroup"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedStudyGroup"];
                "multipart/form-data": components["schemas"]["PatchedStudyGroup"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudyGroup"];
                };
            };
        };
    };
    study_group_attendance_history_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this study group. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudyGroup"];
                };
            };
        };
    };
    study_group_cancel_request_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this study group. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StudyGroup"];
                "application/x-www-form-urlencoded": components["schemas"]["StudyGroup"];
                "multipart/form-data": components["schemas"]["StudyGroup"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudyGroup"];
                };
            };
        };
    };
    study_group_join_request_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this study group. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StudyGroup"];
                "application/x-www-form-urlencoded": components["schemas"]["StudyGroup"];
                "multipart/form-data": components["schemas"]["StudyGroup"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudyGroup"];
                };
            };
        };
    };
    study_group_sessions_list_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this study group. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudyGroup"];
                };
            };
        };
    };
    study_group_invite_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StudyGroup"];
                "application/x-www-form-urlencoded": components["schemas"]["StudyGroup"];
                "multipart/form-data": components["schemas"]["StudyGroup"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudyGroup"];
                };
            };
        };
    };
    subject_list: {
        parameters: {
            query?: {
                name?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedSubjectList"];
                };
            };
        };
    };
    subject_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Subject"];
                "application/x-www-form-urlencoded": components["schemas"]["Subject"];
                "multipart/form-data": components["schemas"]["Subject"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Subject"];
                };
            };
        };
    };
    subject_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this subject. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Subject"];
                };
            };
        };
    };
    subject_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this subject. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Subject"];
                "application/x-www-form-urlencoded": components["schemas"]["Subject"];
                "multipart/form-data": components["schemas"]["Subject"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Subject"];
                };
            };
        };
    };
    subject_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this subject. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    subject_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this subject. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedSubject"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedSubject"];
                "multipart/form-data": components["schemas"]["PatchedSubject"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Subject"];
                };
            };
        };
    };
    user_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedSimpleUserList"];
                };
            };
        };
    };
    user_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SimpleUser"];
                "application/x-www-form-urlencoded": components["schemas"]["SimpleUser"];
                "multipart/form-data": components["schemas"]["SimpleUser"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimpleUser"];
                };
            };
        };
    };
    user_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this user. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimpleUser"];
                };
            };
        };
    };
    user_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this user. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SimpleUser"];
                "application/x-www-form-urlencoded": components["schemas"]["SimpleUser"];
                "multipart/form-data": components["schemas"]["SimpleUser"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimpleUser"];
                };
            };
        };
    };
    user_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this user. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    user_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this user. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedSimpleUser"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedSimpleUser"];
                "multipart/form-data": components["schemas"]["PatchedSimpleUser"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimpleUser"];
                };
            };
        };
    };
    user_profile_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this user. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimpleUser"];
                };
            };
        };
    };
    user_me_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimpleUser"];
                };
            };
        };
    };
    user_stats_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimpleUser"];
                };
            };
        };
    };
}
