# Generated by Django 5.2.8 on 2026-04-06 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0003_membership_delete_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('creator', 'Creator'), ('moderator', 'Moderator'), ('member', 'Member')], default='member', max_length=20),
        ),
        migrations.AlterField(
            model_name='membership',
            name='status',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('rejected', 'Rejected'), ('pending', 'Pending')], default='pending', max_length=10),
        ),
    ]
