# Generated by Django 5.2.8 on 2026-04-09 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0005_attendance_check_out_time_attendance_last_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership', to='study.studygroup'),
        ),
    ]
