# Generated by Django 5.2.8 on 2026-04-11 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0006_alter_membership_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='status',
            field=models.CharField(choices=[('finished', 'Finished'), ('scheduled', 'Scheduled'), ('on_going', 'On Going'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20),
        ),
    ]
